spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: inventory-service
          uri: lb://INVENTORY-SERVICE   # Eureka service name
          predicates:
            - Path=/api/v1/inventory/**

        - id: order-service
          uri: lb://ORDER-SERVICE  # Eureka service name
          predicates:
            - Path=/api/v1/orders/**
        - id: product-service
          uri: lb://PRODUCT-SERVICE  # Eureka service name
          predicates:
            - Path=/api/v1/products/**

        - id: cart-service
          uri: lb://CART-SERVICE  # Eureka service name
          predicates:
            - Path=/api/v1/carts/**

        - id: user-service
          uri: lb://USER-SERVICE  # Eureka service name
          predicates:
            - Path=/api/v1/users/**

        - id: auth-service
          uri: lb://AUTH-SERVICE  # Eureka service name
          predicates:
            - Path=/api/v1/auth/**
      discovery:
        locator:
          enabled: true
#        globalcors:
#          cors-configurations:
#            '[/**]':
#              allowed-origins:
#                - "http://localhost:4200"
#              allowed-methods:
#                - GET
#                - POST
#                - PUT
#                - DELETE
#                - OPTIONS
#              allowed-headers:
#                - Content-Type
#                - Authorization
#                - Access-Control-Allow-Origin
#                - Access-Control-Allow-Credentials
#                - Access-Control-Allow-Headers
#                - Access-Control-Allow-Methods
#              allow-credentials: true
server:
  port: 8222
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
jwt:
  secret: "a14a1ee189918fda411a96a0c9e4d48b9df1ca8eb221a68f5ad6139e8e934eac"