spring:
  cloud:
    gateway:
     routes:
       - id: user-service
         uri: http://localhost:8081
         predicates:
           - Path: /api/v1/users/**
       - id: order-service
         uri: http://localhost:8082
         predicates:
           - Path: /api/v1/orders/**

       - id: product-service
         uri: http://localhost:8083
         predicates:
           - Path: /api/v1/products
       - id: inventory-service
         uri: http://localhost:8084
         predicates:
           - Path: /api/v1/inventories/**
     discovery:
       locator:
         enabled: true
server:
  port: 8222
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761
    instance:
      prefer-ip-adress: true