eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/productservice-db
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8083