spring:
  datasource:
    username: postgres
    password: newpassword
    url: jdbc:postgresql://localhost:5431/userservice-db
  application:
    name: user-service
  jpa:
    hibernate:
      ddl-auto: update
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      database: postgresql
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8081
