eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/orderservice-db
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: Order-service
server:
  port: 8082
